# podman kube --help
# man podman-kube-play
# cd deployment/play # this is important so the image build works
# podman kube play --replace keycloak.yaml
# podman logs keycloak-keycloak
# https://github.com/containers/podman/blob/main/docs/kubernetes_support.md?plain=1
# podman stats
apiVersion: v1
kind: Pod
metadata:
  name: keycloak
spec:
  containers:
    - name: keycloak
      image: keycloak
      args: ["start", "--optimized"]
      env:
        - name: KC_DB_URL
          value: jdbc:postgresql://postgres/postgres
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_DB_PASSWORD
          value: bestpassword # FIXME don't put password here
        - name: KC_HOSTNAME
          value: localhost
        # https://www.keycloak.org/server/enabletls
        # TODO https://www.keycloak.org/server/vault
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: /run/secrets/tls-cert/tls.crt
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value: /run/secrets/tls-cert/tls.key
      volumeMounts:
        - name: keycloak-tls-cert-volume
          mountPath: "/run/secrets/tls-cert"
          readOnly: true
      ports:
        - containerPort: 8443
      resources:
        requests:
          memory: "512Mi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "4"
  volumes:
    - name: keycloak-tls-cert-volume
      secret:
        secretName: keycloak-tls-cert
---
# mkcert keycloak.localhost
