apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - files:
      - tls.crt=keycloak.pem
      - tls.key=keycloak-key.pem
    name: keycloak-tls-cert
    type: kubernetes.io/tls
  - name: application-config
    type: Opaque
    files:
      - tls.cert=perfect-group-allocation.pem
      - tls.key=perfect-group-allocation-key.pem
    literals:
      - openidconnect.client_id=pga
      - openidconnect.client_secret=FIXME
      - openidconnect.issuer_url=https://keycloak/realms/pga
      - database_url=postgres://postgres@postgres/pga?sslmode=disable
      - url=https://perfect-group-allocation
resources:
  - ./keycloak.yaml
  - ./postgres.yaml
  - ./webdriver.yaml
  - ./perfect-group-allocation.yaml
