apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: application-config
    type: Opaque
    files:
      - tls.cert=perfect-group-allocation.pem
      - tls.key=perfect-group-allocation-key.pem
      - openidconnect.client_secret=client-secret
    literals:
      - openidconnect.client_id=pga
      - openidconnect.issuer_url=https://keycloak/realms/pga
      - database_url=postgres://postgres@postgres/pga?sslmode=disable
      - url=https://perfect-group-allocation
resources:
  - ./test.yaml
  - ./perfect-group-allocation.yaml
