apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - files:
      - tls.crt=keycloak.localhost.pem
      - tls.key=keycloak.localhost-key.pem
    name: keycloak-tls-cert
    type: kubernetes.io/tls
  - name: application-config
    type: Opaque
    files:
      - tls.cert=
    literals:
      - TEST=hi
resources:
  - ./keycloak.yaml
  - ./postgres.yaml
  - ./webdriver.yaml
  - ./perfect-group-allocation.yaml
