# podman kube --help
# man podman-kube-play
# podman kube play --replace deployment/play/postgres.yaml
# https://github.com/containers/podman/blob/main/docs/kubernetes_support.md?plain=1
# podman stats

# podman secret ls
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: bestpassword # TODO FIXME don't put this here
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: docker.io/library/postgres:16.1
      env:
        - name: "POSTGRES_INITDB_ARGS"
          value: "--data-checksums"
          # maybe switch to mtls at some point?
          # https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume
        - name: "POSTGRES_PASSWORD_FILE"
          value: "/etc/postgres-secret-volume/password"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-volume
        - name: postgres-secret-volume
          mountPath: "/etc/postgres-secret-volume"
          readOnly: true
      ports:
        - containerPort: 5432
      resources:
        requests:
          memory: "512Mi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "4"
  volumes:
    - name: postgres-secret-volume
      secret:
        secretName: postgres-secret
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
