apiVersion: v1
kind: Pod
metadata:
  name: webdriver-pod
  annotations:
    io.podman.annotations.userns: keep-id
spec:
  containers:
    - command:
        - ls
        - "-ln"
        - "/tmp"
      env:
        - name: WAYLAND_DISPLAY
          value: wayland-0
      image: localhost/firefoxy:latest
      name: webdriver
      resources:
        requests:
          memory: "512Mi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "4"
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumeMounts:
        # socket has wrong user
        - mountPath: /tmp/wayland-0
          name: run-user-1000-wayland-0-host-0
          readOnly: true
        - name: dev-dri-host-1
          mountPath: /dev/dri
  hostUsers: true
  volumes:
    - hostPath:
        path: /run/user/1000/wayland-0
        type: File
      name: run-user-1000-wayland-0-host-0
    - name: dev-dri-host-1
      hostPath:
        path: /dev/dri
        type: Directory
# podman --log-level=debug kube play --replace ../webdriver.yaml  &&  podman logs webdriver-pod-webdriver
