[package]
name = "perfect-group-allocation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good_lp = { default-features = false, version = "1", features = [ "coin_cbc" ] }
itertools = { default-features = false, version = "0.11", features = [ "use_alloc", "use_std" ] }
nanoserde = { default-features = false, version = "0.1" }
