cargo-features = ["edition2024"]

[package]
name = "perfect-group-allocation"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
repository = "https://github.com/projektwahl/perfect-group-allocation"
description = "Allocate people to groups according to their preferences while honoring specified restrictions."
keywords = ["web", "management", "service"]
categories = ["web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
good_lp = { default-features = false, version = "1", features = [ "coin_cbc" ] }
itertools = { default-features = false, version = "0.12", features = [ "use_alloc", "use_std" ] }
tokio = { version = "1", features = ["full", "tracing"] }
tracing = { version = "0.1", features = ["release_max_level_off"] }
log = { version = "0.4", features = ["release_max_level_off"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sea-orm = { version = "0.12", features = [ "sqlx-mysql", "sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
sea-orm-migration = "0.12"
axum = { version = "0.7", features = [ "http2", "macros", "multipart", "tracing" ] }
axum-server = { version = "0.6", features = ["tls-rustls"] }
tokio-rustls = "0.25"
hyper = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }
http-body = "1"
tokio-util = { version = "0.7", features = ["io"] }
anyhow = "1"
sqlx = "0.7"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
axum-extra = { version = "0.9", features = ["cookie", "cookie-private", "cookie-signed", "typed-header"] }
rand = "0.8"
lightningcss = "1.0.0-alpha.49"
parcel_sourcemap = "2"
thiserror = "1"
openidconnect = "3"
oauth2 = "4"
reqwest = { version = "0.11", features = ["json"] }
once_cell = "1"
chrono = "0.4"
miniserde = "0.1"
http = "1"
console-subscriber = "0.2"
tokio-metrics = { version = "0.3" }
zero-cost-templating = { path = "../zero-cost-templating/zero-cost-templating" }

[profile.release]
debug = 1
