[package]
name = "perfect-group-allocation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good_lp = "1.6.1"
nanoserde = { default-features = false, version = "0.1.35" }
