[workspace]
resolver = "2"
members = [
    "perfect-group-allocation-backend", "perfect-group-allocation-e2e", "perfect-group-allocation-database"
, "webdriver-bidi"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "AGPL-3.0-or-later"
repository = "https://github.com/projektwahl/perfect-group-allocation"
description = "Allocate people to groups according to their preferences while honoring specified restrictions."
keywords = ["web", "management", "service"]
categories = ["web-programming"]
readme = "README.md"

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
cargo = "warn"
missing_errors_doc = "allow"
