[package]
name = "perfect-group-allocation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
futures-util = "0.3"
good_lp = { default-features = false, version = "1", features = [ "coin_cbc" ] }
itertools = { default-features = false, version = "0.11", features = [ "use_alloc", "use_std" ] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
sea-orm = { version = "0.12", features = [ "sqlx-mysql", "sqlx-postgres", "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
sea-orm-migration = "0.12"
axum = { version = "0.6", features = [ "http2", "macros", "multipart", "tracing" ] }
rustls-pemfile = "1.0.3"
tokio-rustls = "0.24.1"
hyper = "0.14.27"
tower = "0.4.13"
