[workspace]
resolver = "2"

members = [
    "perfect-group-allocation-backend",
]

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
cargo = "warn"
