[workspace]
resolver = "2"
members = [
    "perfect-group-allocation-backend", "perfect-group-allocation-e2e", "perfect-group-allocation-database"
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "AGPL-3.0-or-later"
repository = "https://github.com/projektwahl/perfect-group-allocation"
description = "Allocate people to groups according to their preferences while honoring specified restrictions."
keywords = ["web", "management", "service"]
categories = ["web-programming"]
readme = "README.md"

[profile.release-with-debug]
inherits = "release"
debug = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"
nursery = "warn"
cargo = "warn"

[patch.crates-io]
proc-macro-crate = { git = "https://github.com/westy92/proc-macro-crate", rev = "89166accf43a380a7a8e66c2eea20ce4fd9dae8f" }
