receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
  otlp/opensearch:
    endpoint: opensearch-data-prepper:21890
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://localhost:9090/api/v1/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/jaeger
        - otlp/opensearch
        - otlphttp/prometheus
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/jaeger
        - otlp/opensearch
        - otlphttp/prometheus
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/jaeger
        - otlp/opensearch
        - otlphttp/prometheus
