receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
  otlphttp/opensearch:
    traces_endpoint: http://opensearch-data-prepper:21890
    metrics_endpoint: http://opensearch-data-prepper:21890
    logs_endpoint: http://opensearch-data-prepper:21890

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/jaeger
        - otlphttp/opensearch
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/jaeger
        - otlphttp/opensearch
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/jaeger
        - otlphttp/opensearch
