name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: docker
    container:
      image: node:slim
    steps:
      - run: apt update && apt install -y zstd curl mold coinor-libcbc-dev
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/      
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
      - run: rustup toolchain install --component rustfmt,clippy nightly
      - run: rustup default nightly
      - run: cargo install --locked cargo-hack
      - run: cargo install --locked cargo-deny
      - uses: actions/checkout@v3
      - run: cargo fmt --check
      - run: cargo hack build --workspace --feature-powerset --optional-deps --all-targets
      - run: cargo hack clippy --workspace --feature-powerset --optional-deps --all-targets -- -D warnings
      - run: cargo hack test --workspace --feature-powerset --optional-deps --all-targets
      - run: cargo deny check
