cargo-features = ["edition2024"]

[package]
name = "perfect-group-allocation-database"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { default-features = false, version = "2" }
diesel-async = { default-features = false, version = "0.4", features = ["postgres", "deadpool"] }
thiserror = { default-features = false, version = "1" }
http = { default-features = false, version = "1" }
async-trait = { default-features = false, version = "0.1" }

[lints]
workspace = true
