apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
type: Opaque
stringData:
  password: keycloak-bestpassword # TODO FIXME don't put this here, maybe use tls authentication with the postgres cert?
---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-postgres
  #annotations:
  #io.podman.annotations.infra.name: keycloak-postgres-infra
spec:
  restartPolicy: OnFailure
  containers:
    - name: postgres
      image: docker.io/library/postgres:16.1
      env:
        - name: "POSTGRES_INITDB_ARGS"
          value: "--data-checksums"
        - name: "POSTGRES_PASSWORD_FILE"
          value: "/etc/keycloak-postgres-secret-volume/password"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: keycloak-postgres-volume
        - name: keycloak-postgres-secret-volume
          mountPath: "/etc/keycloak-postgres-secret-volume"
          readOnly: true
      ports:
        - containerPort: 5432
      startupProbe:
        exec:
          command:
            - pg_isready
        periodSeconds: 3
        failureThreshold: 30
      livenessProbe:
        exec:
          command:
            - pg_isready
        periodSeconds: 3
      resources:
        limits:
          memory: "1Gi"
          cpu: "4"
  volumes:
    - name: keycloak-postgres-secret-volume
      secret:
        secretName: keycloak-postgres-secret
    - name: keycloak-postgres-volume
      persistentVolumeClaim:
        claimName: keycloak-postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
