apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - files:
      - tls.crt=keycloak.pem
      - tls.key=keycloak-key.pem
    name: keycloak-tls-cert
    type: kubernetes.io/tls
resources:
  - ./postgres.yaml
  - ./keycloak.yaml
