cargo-features = ["edition2024"]

[package]
name = "perfect-group-allocation-config"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figment = { version = "0.10", features = ["toml", "env"] }
serde = { default-features = false, version = "1", features = ["derive"] }
thiserror = { default-features = false, version = "1" }

[lints]
workspace = true
