{{- if .Values.pga.enable -}}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "perfect-group-allocation.fullname" . }}-perfect-group-allocation"
spec:
  restartPolicy: OnFailure
  securityContext:
    sysctls:
      - name: net.ipv4.ip_unprivileged_port_start
        value: "443"
  containers:
    - name: perfect-group-allocation
      image: perfect-group-allocation:NOTFOUND
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      env:
        - name: PGA_CONFIG_DIR
          value: /run/secrets
        - name: RUST_LOG
          value: info
        - name: SSL_CERT_FILE
          value: /run/rootCA/rootCA.pem
      volumeMounts:
        - name: secret-volume
          mountPath: "/run/secrets"
          readOnly: true
        - name: root-ca
          mountPath: "/run/rootCA"
          readOnly: true
        {{- if eq .Values.mode "development" }}
        - name: code
          mountPath: /home/podman/app
        {{- end }}
      #ports:
      #  - containerPort: 443
      #livenessProbe:
      #  # for kubernetes use an http check and don't bundle curl with the container.
      #  exec:
      #    command:
      #      - "curl"
      #      - "--fail-with-body"
      #      - "--insecure"
      #      - "https://localhost:8443/health/live"
      #  periodSeconds: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "1"
        limits:
          memory: "1Gi"
          cpu: "4"
  volumes:
    - name: secret-volume
      secret:
        secretName: application-config
    - name: root-ca
      configMap:
        name: root-ca
    {{- if eq .Values.mode "development" }}
    - name: code
      hostPath:
        path: {{ .Values.projectdir | required "projectdir is required in development mode" | quote }}
        type: Directory
    {{- end }}
{{- end }}
