apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "perfect-group-allocation.name" . }}-postgres-secret"
type: Opaque
stringData:
  password: bestpassword # TODO FIXME don't put this here, maybe use tls authentication
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "perfect-group-allocation.name" . }}-postgres
  #annotations:
  #io.podman.annotations.infra.name: postgres-infra
spec:
  restartPolicy: OnFailure
  containers:
    - name: postgres
      image: docker.io/library/postgres:16.1
      env:
        - name: "POSTGRES_INITDB_ARGS"
          value: "--data-checksums"
        - name: "POSTGRES_PASSWORD_FILE"
          value: "/etc/postgres-secret-volume/password"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-volume
        - name: postgres-secret-volume
          mountPath: "/etc/postgres-secret-volume"
          readOnly: true
      ports:
        - containerPort: 5432
      startupProbe:
        exec:
          command:
            - pg_isready
        periodSeconds: 3
        failureThreshold: 30
      livenessProbe:
        exec:
          command:
            - pg_isready
        periodSeconds: 3
      resources:
        limits:
          memory: "1Gi"
          cpu: "4"
  volumes:
    - name: postgres-secret-volume
      secret:
        secretName: "{{ include "perfect-group-allocation.name" . }}-postgres-secret"
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: "{{ include "perfect-group-allocation.name" . }}-postgres-claim"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "perfect-group-allocation.name" . }}-postgres-claim"
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
