name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y coinor-libcbc-dev
      - run: rustup default nightly
      - uses: actions/checkout@v3
      - run: cargo build
      - run: cargo test
  clippy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y coinor-libcbc-dev
      - run: rustup toolchain install nightly --component clippy
      - run: rustup default nightly
      - uses: actions/checkout@v3
      - run: cargo clippy --all-targets --all-features -- -D warnings
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y coinor-libcbc-dev
      - run: rustup default nightly
      - run: cargo install --locked cargo-deny
      - uses: actions/checkout@v3
      - run: cargo fmt --check
      - run: cargo deny check
