name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

# only test latest commit on ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest # doesn't have a recent enough podman version
    steps:
      - run: brew install podman
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/containers/
          key: containers-cache
      - uses: actions/checkout@v4
      # what does privileged here affect and can we remove it?
      # -v /run/user/1000/wayland-0:/run/user/1000/wayland-0 # not in CI
      - run: podman run -it --device /dev/dri --privileged --userns=keep-id:uid=1000,gid=1000 -v pga-podman-cache:/home/podman/.local/share/containers -v pga-cargo:/home/podman/.cargo -v pga-target:$PWD/target -v $PWD:$PWD --workdir=$PWD ghcr.io/projektwahl/perfect-group-allocation:1 sh -c ./.github/run.sh
