name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt-build-deny-check:
    #runs-on: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/projektwahl/perfect-group-allocation
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/      
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: cargo hack build --workspace --feature-powerset --optional-deps --all-targets
      - run: cargo deny check
  clippy:
    #runs-on: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/projektwahl/perfect-group-allocation
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/      
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions/checkout@v4
      - run: cargo hack clippy --workspace --feature-powerset --optional-deps --all-targets -- -D warnings
  test:
    #runs-on: docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/projektwahl/perfect-group-allocation
      options: --privileged --cap-add NET_BIND_SERVICE --sysctl net.ipv4.ip_unprivileged_port_start=0 --add-host h3.selfmade4u.de:127.0.0.1 # for valgrind
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/      
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - uses: actions/checkout@v4
      - run: mkcert -install
      - run: cp $(mkcert -CAROOT)/rootCA.pem .
      - run: mkcert h3.selfmade4u.de
      - run: RUST_BACKTRACE=1 cargo hack test --workspace --feature-powerset --optional-deps --all-targets
