name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt install -y coinor-libcbc-dev
    - run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all-targets --all-features
