name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y mold coinor-libcbc-dev
      - run: cargo +stable install cargo-hack --locked
      - run: rustup default nightly
      - uses: actions/checkout@v3
      - run: cargo hack build --workspace --feature-powerset --optional-deps --all-targets
      - run: cargo hack test --workspace --feature-powerset --optional-deps --all-targets
  clippy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y mold coinor-libcbc-dev
      - run: cargo +stable install cargo-hack --locked
      - run: rustup toolchain install nightly --component clippy
      - run: rustup default nightly
      - uses: actions/checkout@v3
      - run: cargo hack clippy --workspace --feature-powerset --optional-deps --all-targets -- -D warnings
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y mold coinor-libcbc-dev
      - run: rustup toolchain install nightly --component rustfmt
      - run: rustup default nightly
      - run: cargo install --locked cargo-deny
      - uses: actions/checkout@v3
      - run: cargo fmt --check
      - run: cargo deny check
