name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

# only test latest commit on ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest # doesn't have a recent enough podman version. we want to avoid docker at all costs because it adds another layer of complexity
    steps:
      # https://github.com/containers/podman/issues/10422
      - run: sudo usermod --del-subuids 165536-231071 --del-subgids 165536-231071 --add-subuids 300000-400000 --add-subgids 300000-400000 $USER # TODO probably remove old mapping
      - run: cat /etc/subuid
      - run: NONINTERACTIVE=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
      - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install podman
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/containers/
          key: containers-cache
      - uses: actions/checkout@v4
      - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && podman --version
      - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && podman unshare cat /proc/self/uid_map
      # what does privileged here affect and can we remove it?
      # -v /run/user/1000/wayland-0:/run/user/1000/wayland-0 # not in CI
      # https://github.com/containers/podman/issues/16541
      # https://www.redhat.com/sysadmin/debug-rootless-podman-mounted-volumes
      # https://www.redhat.com/sysadmin/rootless-podman
      # I think we need to create a custom mapping here to make this work for arbitrary host subuids as the subuids inside of the container are fixed
      # https://docs.podman.io/en/latest/markdown/podman-run.1.html#uidmap-flags-container-uid-from-uid-amount
      # Error: container ID 0 cannot be mapped to a host ID probably means we forgot to map that id to some host id
      # IMPORTANT: when you change the mapping here you need to delete the container volume
      - run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && podman run --rm -it --device /dev/dri --privileged --uidmap 1000:0:1 --uidmap 0:1:1000 --uidmap 100000:1001:65536 -v pga-podman-cache:/home/podman/.local/share/containers -v pga-cargo:/home/podman/.cargo -v pga-target:$PWD/target -v $PWD:$PWD --workdir=$PWD ghcr.io/projektwahl/perfect-group-allocation:1 sh -c ./.github/run.sh
